[2024-10-18T13:23:22.654+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:23:22.674+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.this_is_1st_task scheduled__2022-06-13T00:00:00+00:00 [queued]>
[2024-10-18T13:23:22.691+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.this_is_1st_task scheduled__2022-06-13T00:00:00+00:00 [queued]>
[2024-10-18T13:23:22.693+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:23:22.731+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_1st_task> on 2022-06-13 00:00:00+00:00
[2024-10-18T13:23:22.743+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4069) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:23:22.745+0000] {standard_task_runner.py:72} INFO - Started process 4084 to run task
[2024-10-18T13:23:22.745+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'this_is_1st_task', 'scheduled__2022-06-13T00:00:00+00:00', '--job-id', '2273', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp4f6w0zv5']
[2024-10-18T13:23:22.755+0000] {standard_task_runner.py:105} INFO - Job 2273: Subtask this_is_1st_task
[2024-10-18T13:23:23.181+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v3.this_is_1st_task scheduled__2022-06-13T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:23:23.347+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='this_is_1st_task' AIRFLOW_CTX_EXECUTION_DATE='2022-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-06-13T00:00:00+00:00'
[2024-10-18T13:23:23.348+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:23:23.372+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:23:23.376+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my first task']
[2024-10-18T13:23:23.741+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:23:23.764+0000] {subprocess.py:93} INFO - Hello world, this is my first task
[2024-10-18T13:23:23.773+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:23:24.042+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:23:24.047+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=this_is_1st_task, run_id=scheduled__2022-06-13T00:00:00+00:00, execution_date=20220613T000000, start_date=20241018T132322, end_date=20241018T132324
[2024-10-18T13:23:24.466+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:23:24.618+0000] {taskinstance.py:3900} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-10-18T13:23:24.622+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
