[2024-10-18T13:30:46.867+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:30:46.875+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2023-04-09T00:00:00+00:00 [queued]>
[2024-10-18T13:30:46.885+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2023-04-09T00:00:00+00:00 [queued]>
[2024-10-18T13:30:46.892+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:30:47.137+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_2nd_task> on 2023-04-09 00:00:00+00:00
[2024-10-18T13:30:47.148+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=12757) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:30:47.151+0000] {standard_task_runner.py:72} INFO - Started process 12776 to run task
[2024-10-18T13:30:47.152+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'this_is_2nd_task', 'scheduled__2023-04-09T00:00:00+00:00', '--job-id', '4370', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp0_wa93cg']
[2024-10-18T13:30:47.155+0000] {standard_task_runner.py:105} INFO - Job 4370: Subtask this_is_2nd_task
[2024-10-18T13:30:47.425+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2023-04-09T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:30:47.672+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='this_is_2nd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-09T00:00:00+00:00'
[2024-10-18T13:30:47.678+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:30:47.724+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:30:47.732+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my second task and will run after task one ']
[2024-10-18T13:30:47.789+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:30:47.802+0000] {subprocess.py:93} INFO - Hello world, this is my second task and will run after task one
[2024-10-18T13:30:47.803+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:30:47.870+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:30:47.875+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=this_is_2nd_task, run_id=scheduled__2023-04-09T00:00:00+00:00, execution_date=20230409T000000, start_date=20241018T133046, end_date=20241018T133047
[2024-10-18T13:30:48.025+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:30:48.179+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-18T13:30:48.195+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
