[2024-10-18T13:28:04.070+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:28:04.106+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_1st_task scheduled__2022-04-25T00:00:00+00:00 [queued]>
[2024-10-18T13:28:04.132+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_1st_task scheduled__2022-04-25T00:00:00+00:00 [queued]>
[2024-10-18T13:28:04.133+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:28:04.219+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_1st_task> on 2022-04-25 00:00:00+00:00
[2024-10-18T13:28:04.228+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8418) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:28:04.237+0000] {standard_task_runner.py:72} INFO - Started process 8436 to run task
[2024-10-18T13:28:04.230+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'this_is_1st_task', 'scheduled__2022-04-25T00:00:00+00:00', '--job-id', '3302', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpj4g4inb3']
[2024-10-18T13:28:04.239+0000] {standard_task_runner.py:105} INFO - Job 3302: Subtask this_is_1st_task
[2024-10-18T13:28:04.399+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.this_is_1st_task scheduled__2022-04-25T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:28:04.524+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='this_is_1st_task' AIRFLOW_CTX_EXECUTION_DATE='2022-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-04-25T00:00:00+00:00'
[2024-10-18T13:28:04.526+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:28:04.550+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:28:04.553+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my first task']
[2024-10-18T13:28:04.601+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:28:04.602+0000] {subprocess.py:93} INFO - Hello world, this is my first task
[2024-10-18T13:28:04.603+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:28:04.680+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:28:04.681+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=this_is_1st_task, run_id=scheduled__2022-04-25T00:00:00+00:00, execution_date=20220425T000000, start_date=20241018T132804, end_date=20241018T132804
[2024-10-18T13:28:04.908+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:28:04.956+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
