[2024-10-18T13:22:24.108+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:22:24.193+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.this_is_2nd_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2024-10-18T13:22:24.239+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.this_is_2nd_task scheduled__2022-01-25T00:00:00+00:00 [queued]>
[2024-10-18T13:22:24.241+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:22:24.311+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_2nd_task> on 2022-01-25 00:00:00+00:00
[2024-10-18T13:22:24.341+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2439) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:22:24.345+0000] {standard_task_runner.py:72} INFO - Started process 2456 to run task
[2024-10-18T13:22:24.340+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'this_is_2nd_task', 'scheduled__2022-01-25T00:00:00+00:00', '--job-id', '1873', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpr52k9489']
[2024-10-18T13:22:24.346+0000] {standard_task_runner.py:105} INFO - Job 1873: Subtask this_is_2nd_task
[2024-10-18T13:22:24.490+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v3.this_is_2nd_task scheduled__2022-01-25T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:22:24.679+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='this_is_2nd_task' AIRFLOW_CTX_EXECUTION_DATE='2022-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-01-25T00:00:00+00:00'
[2024-10-18T13:22:24.683+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:22:24.712+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:22:24.716+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my second task and will run after task one ']
[2024-10-18T13:22:24.729+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:22:24.731+0000] {subprocess.py:93} INFO - Hello world, this is my second task and will run after task one
[2024-10-18T13:22:24.732+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:22:24.774+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:22:24.777+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=this_is_2nd_task, run_id=scheduled__2022-01-25T00:00:00+00:00, execution_date=20220125T000000, start_date=20241018T132224, end_date=20241018T132224
[2024-10-18T13:22:24.849+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:22:24.933+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
