[2024-10-18T13:35:40.792+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:35:40.805+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_1st_task scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-10-18T13:35:40.818+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_1st_task scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-10-18T13:35:40.819+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:35:40.871+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_1st_task> on 2024-04-19 00:00:00+00:00
[2024-10-18T13:35:40.886+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=17321) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:35:40.896+0000] {standard_task_runner.py:72} INFO - Started process 17330 to run task
[2024-10-18T13:35:40.885+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'this_is_1st_task', 'scheduled__2024-04-19T00:00:00+00:00', '--job-id', '5484', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpfq0d8hdm']
[2024-10-18T13:35:40.900+0000] {standard_task_runner.py:105} INFO - Job 5484: Subtask this_is_1st_task
[2024-10-18T13:35:41.017+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.this_is_1st_task scheduled__2024-04-19T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:35:41.167+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='this_is_1st_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-19T00:00:00+00:00'
[2024-10-18T13:35:41.170+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:35:41.211+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:35:41.214+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my first task']
[2024-10-18T13:35:41.242+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:35:41.244+0000] {subprocess.py:93} INFO - Hello world, this is my first task
[2024-10-18T13:35:41.245+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:35:41.313+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:35:41.315+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=this_is_1st_task, run_id=scheduled__2024-04-19T00:00:00+00:00, execution_date=20240419T000000, start_date=20241018T133540, end_date=20241018T133541
[2024-10-18T13:35:41.383+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:35:41.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
